import type { Metadata } from "next";
import "./bootstrap.min.css";
import Navbar from "./topnotch-proto/Navbar";
import "./globals.css";
import SmoothScroll from "./SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScroll>
      <html lang="en">
        <body>
          <Navbar />
            {children}
        </body>
      </html>
    </SmoothScroll>
  );
}