import type { Metadata } from 'next'
import './bootstrap.min.css'
import Navbar from './topnotch-proto/Navbar'
import Footer from './topnotch-proto/footer'
import './globals.css'
import SmoothScroll from './SmoothScroll'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SmoothScroll>
      <html lang='en'>
        <head>
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1.0'
          />
        </head>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </SmoothScroll>
  )
}
